export const ADD_FLASH_MESSAGE = "ADD";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const FETCH_USER_INFO = "FETCH_USER_INFO";
export const FETCH_USERS_INFO = "FETCH_USERS_INFO";
export const FETCH_USER_PRODUCTS = "FETCH_USER_PRODUCTS";
export const FETCH_IMAGE_PRODUCT = "FETCH_IMAGE_PRODUCT";
export const FETCH_IMAGE_USER = "FETCH_IMAGE_USER";

export const UPLOAD_IMAGE_PRODUCT = "UPLOAD_IMAGE_PRODUCT";
export const UPLOAD_IMAGE_USER = "UPLOAD_IMAGE_USER";

export const CLEAN_USER_CONTACTS = "CLEAN_USER_CONTACTS";
export const CLEAN_USER_PRODUCTS = "CLEAN_USER_PRODUCTS";
export const CLEAN_SELECTED_USER = "CLEAN_SELECTED_USER";
export const CLEAN_SEARCH_RESULTS = "CLEAN_SEARCH_RESULTS";
export const CLEAN_SELECTED_PRODUCT = "CLEAN_SELECTED_PRODUCT";
export const CLEAN_IMAGE_PRODUCT = "CLEAN_IMAGE_PRODUCT";
export const CLEAN_IMAGE_USER = "CLEAN_IMAGE_USER";

